### ISSUE TITLE
Build script displays ambiguous error message despite successful build in UNIXLIKE environments

### ISSUE THREAD

**Issue by tim-cotten** [mochimodev/mochimo#1]
**Environment:** UNIXLIKE
**Test environment:** Ubuntu 16.04 LTS

**Expected behavior:**

- `./makeunx bin` will yield an error message on error, and success message on success

**Actual behavior:**

- ./makeunx bin ALWAYS yields a console message `"Error messages are in ccerror.log"`
- This ambiguity is confusing to the user and the build appears unsuccessful even if it was

**Proposed action:**
Check the ccerror.log file size and if it's empty, display "Build successful", otherwise, keep the current behavior.

**Comment by mochimodev** [comment]
This item corrected in the upcoming release.
