### ISSUE TITLE
Wallet - Balance Check Failed - V2.0 

### ISSUE THREAD

**Issue by HazelTheOrphanSlayer** [mochimodev/mochimo#16]
When I check my balance from mochi/bin of my 2.0 installation (latest patch) and bupdata, a previous balance is returned but with the message Balance Check Failed.  When I run \wallet from my old V1.9 /mochi/bin it does not fail and returns the updated balance.  Returning to the V2.0 /bin again returns the old balance and does not reflect the updated balance and returns the Balance Check Failed message.

This wallet was created under V1.9.

**Comment by HazelTheOrphanSlayer** [comment]
This same behaviour was verified by another user.

**Comment by HazelTheOrphanSlayer** [comment]
I have verified this from two separate nodes.  both with the same behaviour - fails on v2.0, works on v1.9

**Comment by chrisdigity** [comment]
The problem lies here,
https://github.com/mochimodev/mochimo/blob/9e0df525d1cafdd5cb936596caf341afc34ba8a5/src/wallet.c#L270-L275

The default IP list baked into the wallet is trying to search for IPs that aren't active. 

I'm distracted with larger fixes at the moment but if anyone is willing to have a go, I started an implementation where the wallet will lookup IPs using the startnodes.lst file that is automatically obtained by the node, or directly from the mochimap.net website.
I'm sure someone else has a better implementation though

**Comment by pzmarzly** [comment]
I tried to get wallet 2.0 working on https://github.com/mochimo-in-a-container/mochimo-in-a-container/tree/beta-2.0 . Even with `-a<IP from mochimap>` it doesn't want to connect. With e.g. `-a65.151.42.12` (defined [here](https://github.com/mochimo-in-a-container/mochimo-in-a-container/blob/cc4a0261e83b0128db59244f63ef7c3341cf8677/scripts/wallet.sh#L15)), I get:

```text
Fetching peer list
Press ctrl-c to stop...
Trying 65.151.42.12 port 2094...  connectip(): cannot connect() socket.
Trying 65.151.42.33 port 2094...  connectip(): cannot connect() socket.
```

Despite having ports open.

**Comment by chrisdigity** [comment]
Sorry, I forgot to add that the default port set in the wallet is 2094, where it should be 2095. To get the `-a<IP>` command to work you must also use `-p2095` in the command

**Comment by pzmarzly** [comment]
Thanks, that fixed my issue. https://github.com/mochimo-in-a-container/mochimo-in-a-container now works with 2.0.

**Comment by chrisdigity** [comment]
Doing up a fix for this right now, that involves removing the default TestNet IP's in `Coreplist`, replacing them with a simple Localhost IP `0x0100007f` and reading in IP's from a `startnodes.lst` file to be used by the wallet. On top of that, I've also added a single line of code to progress the `Coreplist` of IP's such that if you encounter a balance check failed notice, you will be able to quickly "check again" with another node and hopefully have much better results.
Does anyone have any further opinions, suggestions on the matter?

**Comment by mochimodev** [comment]
Closing this issue now.  Chris, when you have time please update the wallet to pull the startnodes.lst from mochimap.net when it is not otherwise available on the disk.
