### ISSUE TITLE
OSX Wallet fails with dylib not found error

### ISSUE THREAD

**Issue by drag0ng** [mochimodev/mochimo#21]
On OSX, since all the dylibs are linked with their "@rpath", all the binaries mcm builds would fail with dylib not found error as the rpath is not being added at compilation time.

Adding rpath fixes the problem. Attached the patch.
[osx_patch.txt](https://github.com/mochimodev/mochimo/files/2575172/osx_patch.txt)

**Comment by mochimodev** [comment]
drag0ng - I'm happy to merge in this fix, please submit it as a pull request.  Note you'll get two bounties, one for submitting the issue and another for submitting a proper pull request.

**Comment by drag0ng** [comment]
I actually tried to push a branch. But I guess I don't have permissions.

**Comment by drag0ng** [comment]
nvm. I'll fork and try

**Comment by drag0ng** [comment]
Closing after creation of PR
