### ISSUE TITLE
./resume does not sync correctly with the active chain.

### ISSUE THREAD

**Issue by HazelTheOrphanSlayer** [mochimodev/mochimo#23]
When using ./resume the miner did not sync the contents of /bc with the active chain before resuming mining.   Result was that the miner bagan solving on an orphan chain one block beyond what was the current block when the miner was stopped with Ctrl-C instead of synching up and starting with the main chain current block.

Behavior was repeated on two different occasions after quitting and resuming.

**Comment by mochimodev** [comment]
If you resume and leave the system alone for long enough to get multiple blocks behind the main chain, then upon resuming the first BLOCK_FOUND received from the network will cause the node to either catch up or go out to contention.  Pausing and resuming the system should happen within a few minutes of eachother.  As such this is operating as designed and is not an issue.  Closing issue.
