### ISSUE TITLE
Can't search for particular blocks on bx explorer in advanced search field

### ISSUE THREAD

**Issue by BreganovTheGreat** [mochimodev/mochimo#24]
If you try to search for a particular block on bx explorer ("advanced search" field), either by filling in decimal or hexadecimal format, it will only leads you to bx explorer main page with most recent blocks.
Exemple, if you want to find block #20023 (0x4e37), it will load https://bx.mochimo.org/? (with Chrome) or https://bx.mochimo.org (Firefox & Vivaldi) instead of  https://bx.mochimo.org/block/20023.

**Comment by mochimodev** [comment]
Thank you, I am reviewing this.

**Comment by chrisdigity** [comment]
This issue has since been fixed with the latest updates of the block explorer allowing the selection of search types (Tags, Blocks, Addresses, Transactions).
@mochimodev you may close this...

**Comment by mochimodev** [comment]
Closing on recommendation of chrisdigity.
