### ISSUE TITLE
Orphan double Haiku Output Error

### ISSUE THREAD

**Issue by HazelTheOrphanSlayer** [mochimodev/mochimo#30]
At least in the case of orphans, a double Haiku is written where the first Haiku is the incorrect (losing) Haiku and the winning Haiku follows.  An example was posted by user FlyingW in the #bestHaiku channel on Discord.   Chrisdigity believes it may be an output bug.

**Comment by chrisdigity** [comment]
I believe I have fixed this in my dev_branch fork. It's under testing at present with good results so far.

**Comment by chrisdigity** [comment]
This should now be fixed as part of the latest merged pull request. The issue was the result of improper pointer handling that was introduced during my multi-GPU CUDA implementation.
13c3034bbe49d7baea23b7af4f1d0b6d8e509212

@mochimodev can close this issue.

**Comment by mochimodev** [comment]
This issue resolved.
