### ISSUE TITLE
Exit program if eon cannot be performed N times

### ISSUE THREAD

**Issue by 0rtis** [mochimodev/mochimo#32]
Miner should exit if the eon quorum cannot be reached N times. The gomochi script must be modified so the startnodes.lst is inside the while loop.

These modifications should prevent the nodes to get stuck after a contention

**Comment by chrisdigity** [comment]
Not sure what you mean by the first part, but I've had the second part included in my dev_branch for some time now.
Testing has been good, should be just about ready for a pull request...

**Comment by 0rtis** [comment]
Currently, `get_eon` function is an infinite loop if the start nodes are stuck at 0x0. We need to update this function so the program exit if a quorum cannot be reached N time.
This gives a chance to update the start nodes before restarting and trying to reach a quorum again.

**Comment by mochimodev** [comment]
Elevating this issue for inclusion in the upcoming v2.3 release.  Thank you 0rtis.

**Comment by mochimodev** [comment]
Watchdog functionality has been included for the upcoming v2.3 release.  Closing this issue.
