### ISSUE TITLE
AEON block advances difficulty

### ISSUE THREAD

**Issue by HazelTheOrphanSlayer** [mochimodev/mochimo#34]
In situations where the previous block has solved quickly the AEON block dropping at the same difficulty can cause the difficulty to advance.  Possible solution is to exempt AEON blocks from from the retargeting algo.

**Comment by chrisdigity** [comment]
Can you provide an example? I can't seem to find a situation where there has been a double jump in difficulty over a neo-genesis block

**Comment by HazelTheOrphanSlayer** [comment]
I am closing this issue.    What happened is that bx.mochimo.org picked up and reported the AEON block before reporting the previous block had solved.   That gave the appearance that the diff=50 AEON block caused the  diff to go from 49 to 51.

**Comment by mochimodev** [comment]
Thank you for digging into this, guys.
