### ISSUE TITLE
Feature Request:  Set Blocks Updated to Zero after restart.

### ISSUE THREAD

**Issue by HazelTheOrphanSlayer** [mochimodev/mochimo#35]
Blocks updated output in the /gomochi default -t3 does not seem to correlate to anything which yields it useless.   A preferred behavior would be to have it reset to 0 after each restart which would allow for a quick survey to see how many blocks the miner has been alive for.   A gomochi  switch that reset it to zero after loading would be acceptable.

**Comment by mochimodev** [comment]
Would it be better to track MCM accumulated, as opposed to block solves?  We can have the main program loop asynchronously test the mining address account balance, and update that to the system status output rather than blocks solved.  Please advise.

**Comment by mochimodev** [comment]
Blocks updated is not a persistent variable.  Closing this issue.
