### ISSUE TITLE
Mochi Wiki link

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mochimo#38]
If you would, please add a link to [mochiwiki.com](mochiwiki.com) in the `README.md` as well as the [github wiki](https://github.com/mochimodev/mochimo/wiki) so that users can easily find the it.

I think, something as simple as this would help out significantly:
```
Please visit [MochiWiki.com](http://www.mochiwiki.com/w/index.php/Main_Page) for the official Mochimo Wiki page
```

I don't think github permits pull requests for wiki changes, otherwise I'd open a pull request to do this. Or, if they do permit it, I think an initial wiki page needs to be started on the main repo before others can contribute via pull requests.

**Comment by Stoner19** [comment]
I just noticed there isn't a SSL certificate for the wiki either...

**Comment by mochimodev** [comment]
Done.  Thank you.  Please open a separate issue for the SSL cert so we can track it and give you credit for it.
