### ISSUE TITLE
stratum mining

### ISSUE THREAD

**Issue by goodthebest** [mochimodev/mochimo#39]
hey devs, great work! Does MCM allows stratum mining? I couldn't get any guides on the wiki page, please direct me if there is any documentation?

**Comment by mochimodev** [comment]
Stratum mining is not supported on the Mochimo codebase.  However, we have our own pool client in testing right now, and Mochimo Pools should be a reality sometime within the next couple months.

**Comment by goodthebest** [comment]
Hey @mochimodev any progress with in-house pool mining client ?
