### ISSUE TITLE
Better UX for Miner - tell the user what's happening

### ISSUE THREAD

**Issue by phenomeus** [mochimodev/mochimo#40]
„Please wait for the current block to be solved and the next TX arrived. After that you will start mining...“
 
what do you think of this message instead of the 0

this should spare us the same question over and over again.

Understandable question to ask by incoming new miners

**Comment by mochimodev** [comment]
I think this issue is related to the Windows miner, please post this issue on the relevant github repo.

**Comment by chrisdigity** [comment]
@phenomeus I'm gonna submit a pull request with minor adjustments to the the node output as suggested. Please provide the discord handle you use on the Mochimo Discord so I can issue a bounty to you for contributing to the project.
