### ISSUE TITLE
SSL for Wiki page

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mochimo#42]
I noticed there is not a SSL certificate for the Wiki. When time allows, please add one :)

**Comment by Stoner19** [comment]
Just a friendly bump to remind the MCM core team that there still is not a SSL certificate for the wiki site ;)

**Comment by Stoner19** [comment]
Last bump was 431 days ago for SSL on wiki

**Comment by mochimodev** [comment]
Not ignoring you, sorry - I just haven't worked my away around to this yet.

**Comment by chrisdigity** [comment]
https://www.mochiwiki.com/ is now set up with automatic renewals of SSL certificates, thnx.
