### ISSUE TITLE
How to make a GitHub account for the Wiki

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mochimo#43]
# Let's make a GitHub account!

##### Why would we want to make a GitHub account?
Well, Mochimo is a new and exciting, community-driven Quantum-resistant currency that relies on you, the user! With your help and support through GitHub issue tracking and contributions not only will you help make Mochimo better, but you'll also earn bounty rewards paid in MCM! Let's get started!

### Step 1: Registration

  - Navigate to https://GitHub.com
    - On the home page there is a box to input your chosen username, email address, and ultra-secure password, and of course please be sure to read their privacy statement and terms of service:
     ![GitHub registration](https://i.imgur.com/a6VGIS5.png)

  - GitHub will likely ask you to solve an "Enforcement Challenge" to validate that you are in fact human and not a machine, bot, etc.
  
    ![Enforcement Challenge](https://i.imgur.com/805lmYC.png)

  - GitHub will ask you whether you want a free account or a paid account. At this time a free account will be suitable for the purposes of helping with MCM issues. You do not need to check the "Help me set up an organization next" checkbox nor the "Send me updates, GitHub news, offers, and events" unless you are interested in receiving that information.
  
      ![Free or Paid](https://i.imgur.com/FX9uWGV.png)

- The last step here will ask you about your experience and interests. This can be skipped if you chose to.
![Tailor your experience](https://i.imgur.com/A3pU0h8.png)

- You will then get an email asking you to verify your account by clicking the link.
    ![email](https://i.imgur.com/WXl2Wmx.png)

- You now have a GitHub account and are ready to start contributing to Mochimo!
    ![Account](https://i.imgur.com/qxyJ3Aa.png)

### Step 2: Opening Issues
- Navigate to the official Mochimo repository at https://GitHub.com/mochimodev/mochimo
![Mochimo Repo](https://i.imgur.com/wQVoBqy.png)

- Click the *Issues* tab
![Issues](https://i.imgur.com/wQVoBqy.png)

- From here you'll be able to view Issues that are currently open and a work in progress as well as those that have already been addressed/fixed and are now considered to be closed.

- To open a new Issue click the "New issue" button
![New issue](https://i.imgur.com/AZS1mqj.png)
    - Here you will be able to elaborate on the issues and or features you wish to be addressed by the core Mochimo development team
    - If you're not familiar with "Markdown" format used you can familiarize yourself with it here: https://guides.GitHub.com/features/mastering-markdown/. It's format makes reading the issues and feature requests submitted here much easier and is always appreciated!
    - While there is no defined format expected for issues being opened, it is always best to provide as much information as possible. Here is a simple "format" in Markdown for an issue that can be used if you so choose:
    
    ```
    # Expected Behavior
      (Please describe the behavior you are expecting)

    # Current Behavior
      (What is the current behavior?)

    ## Steps to Reproduce
      (Detailed Steps to reproduce the issues described)
        1.
        2.
        3.

    ## Context
      Any further relevant information that may help the development team easier identify the issue
        * Version:
        * Operating System:
        * Hardware:

    ## Logs
      (If you have debug logs you may put them here)
  ```

##### THANKS FOR BEING A PART OF THE MOCHIMO COMMUNITY!

Powered By: [![Mochimo](https://mochimo.org/wp-content/uploads/2018/06/mochimo-pq-logo.svg)](https://mochimo.org/)

**Comment by chrisdigity** [comment]
Great write up @Stoner19.
This is now apart of the Mochimo Wiki at [Make a Github Account](http://www.mochiwiki.com/w/index.php/Make_a_Github_Account)
@mochimodev This can now be closed...

**Comment by mochimodev** [comment]
Closing on recommendation of chrisdigity.  Chris, please ensure we're documenting appropriate bounties for these contributions.
