### ISSUE TITLE
"Labels" use on github issues

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mochimo#44]
As Mochimo grows and more and more users begin to open issues on Github, would the team be willing to consider use of the Labels function on github? This will help differentiate between bugs and feature requests.

**Comment by Stoner19** [comment]
These are the default labels that github already provides, but custom ones can be added:

| Label              | Description                                                        |  
| ------------------ | ------------------------------------------------------------------ |  
| `bug`              | Indicates an unexpected problem or unintended behavior             |  
| `duplicate`        | Indicates similar issues or pull requests                          |  
| `enhancement`      | Indicates new feature requests                                     |  
| `good first issue` | Indicates a good issue for first-time contributors                 |  
| `help wanted`      | Indicates that a maintainer wants help on an issue or pull request |  
| `invalid`          | Indicates that an issue or pull request is no longer relevant      |  
| `question`         | Indicates that an issue or pull request needs more information     |  
| `wontfix`          | Indicates that work won't continue on an issue or pull request     |

**Comment by mochimodev** [comment]
Will discuss with you on Discord.  Thank you.

**Comment by chrisdigity** [comment]
It appears that labels were (at some stage) created but not implemented. I will start implementing them as I go through some of these issues. thnx
