### ISSUE TITLE
Medium spelling on the Main wiki page needs to be corrected

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mochimo#45]
Link to Medium on the main page (http://www.mochiwiki.com/w/index.php/Main_Page) reads as `Read our Meidum articles` but should be `Read our Medium articles`

**Comment by lazyazian** [comment]
Thanks for posting this. Fixed it with the reorg of the main page.

**Comment by chrisdigity** [comment]
@mochimodev This issue can be closed...

**Comment by mochimodev** [comment]
Closing on recommendation of chrisdigity.
