### ISSUE TITLE
Request: add wallet backup by seed words

### ISSUE THREAD

**Issue by angryolk** [mochimodev/mochimo#46]
the current backup method is really complicate, as you will need to back up after every transaction. is it possible to develop a backup/recover to/by seed. so that end user just store the seed somewhere? - aaron

**Comment by mochimodev** [comment]
Yes, this is possible.  I'll talk to Andreas about it to make sure this can't compromise WOTS+, thank you.

**Comment by mochimodev** [comment]
This will be available with the v2.4 wallet, thank you for your patience and for the suggestion.  We are testing it now.

**Comment by chrisdigity** [comment]
Hi, @angryolk. Could you please provide the discord handle you use on the Mochimo Discord so I can issue a bounty to you for contributing to the project?

**Comment by angryolk** [comment]
hi its, aaron#3570

**Comment by mochimodev** [comment]
Closing this issue as the requested feature was added in the v2.4 codebase.
