### ISSUE TITLE
can you mine to the tag?

### ISSUE THREAD

**Issue by angryolk** [mochimodev/mochimo#55]
is there any possibility to mine to the tag but not to the address?

**Comment by lucasan123** [comment]
blackminer f1 could mine to the tag before the fork

**Comment by lucasan123** [comment]
i think mining to the tag is useful because otherwise when you spend an address if you are not mining to a tag you have to change your mining address in the conf of the miner all the times... this feature must be activated soon also by the legit pool

**Comment by Stoner19** [comment]
@lucasan123 when an address is "spent" it's still technically usable. As soon as that address receives a balance more than 500 SatoChi (0.000000500, 9 decimal places, not 8) it will show as a usable address again within the mochimo blockchain.

**Comment by lucasan123** [comment]
@Stoner19  yes but the security of the address is gone. the system uses a One Time Signature scheme , so when you send mcm from one address the private key is exposed, and your funds can be stolen if you continue to use that address. the tag system has come to avoid this, but it hasnt been implemented in the pool yet

**Comment by mochimodev** [comment]
Issue closed as answered.  Tag mining will remain unsupported.  Mining pools may provide this functionality as part of their worker integration, but only at a higher layer.
