### ISSUE TITLE
crypto/sha256.c: No such file or directory

### ISSUE THREAD

**Issue by Vasiliy566** [mochimodev/mochimo#68]
cc: error: crypto/sha256.c: No such file or directory
cc: fatal error: no input files
compilation terminated.

**Comment by mochimodev** [comment]
Are you using the latest version of the software and compiling it using /src/makeunx ?

**Comment by Stoner19** [comment]
@Vasiliy566 can you give specifics on the process in which you tried to compile? Possible that you are just in the wrong directory.

**Comment by Stoner19** [comment]
if compiling on Linux, make sure you are in the `/<user>/mochimo/src` directory, and to compile you run either:
`./makeunx bin -DCUDA` if compiling for mining with CUDA-capable GPUs or
`./makeunx bin -DCPU` to run a CPU only node/miner
