### ISSUE TITLE
BoostLib error

### ISSUE THREAD

**Issue by Vasiliy566** [mochimodev/mochimo#69]
./MCM_Cuda: error while loading shared libraries: libboost_thread.so.1.58.0: cannot open shared object file: No such file or directory

**Comment by Vasiliy566** [comment]
./MCM_Cuda: error while loading shared libraries: libboost_thread.so.1.58.0: cannot open shared object file: No such file or directory

**Comment by Vasiliy566** [comment]
So the solution is run miner this way
```
 LD_LIBRARY_PATH=. ./MCM_Cuda 
```

**Comment by chrisdigity** [comment]
I think the repository you want is https://github.com/krypdkat/MochimoMiner
This repository is not yet involved with pool mining software.
