### ISSUE TITLE
Wallet->Delete address does nothing

### ISSUE THREAD

**Issue by pzmarzly** [mochimodev/mochimo#7]
```text
  Select: 8
Delete address index (1-2): 1
Delete 'test' (y/n)? y
```

It does not delete test.

**Comment by chrisdigity** [comment]
I believe the wallet will never actually DELETE an address. I'm not 100% sure as to why but I find it to be a little bit of a safety net for those who might delete the wrong index by accident.
Looking at the source here:
https://github.com/mochimodev/mochimo/blob/9e0df525d1cafdd5cb936596caf341afc34ba8a5/src/wallet.c#L1607-L1611
I can see that after it receives an input of either 'y' or 'Y', it fills the balance of the address with Zero's, sets the `W_DEL` flag to the entry and writes it back to the wallet.
Could you elaborate on why you think it does nothing?

**Comment by pzmarzly** [comment]
I haven't looked at the code before opening that issue. I agree that it makes sense not to delete an address, but right now it doesn't even hide the address in some places, which is not what the name "Delete address" suggests.

**Comment by chrisdigity** [comment]
Well in terms of not hiding the address index in some places, during my own testing I felt it was sufficiently hidden without inhibiting the user from recovering it in the worst case scenario, so you might have to be specific as to which parts were inconsistent so that I can edit those parts of the code appropriately. Also, I'm open to any alternative approach you or anyone else might have in mind.

**Comment by pzmarzly** [comment]
Address gets hidden in "Display" and "Display change addresses", not in "Edit address name", "Display address in hex", "Delete address" (which is what confused me in the first place), "Export address" (understandable, as it is a way to recover this address - reimporting resets `W_DEL`). Feels weird. Maybe, in order for deleted addresses not to take IDs, a separate "trash can" list could be made? It would be quite time-consuming for a pretty low priority improvement, though.

**Comment by chrisdigity** [comment]
@mochimodev Do you think it would be appropriate if I changed the wording of this to something like "Archive" instead of delete?

**Comment by mochimodev** [comment]
Yes, please change the name to "Hide/Archive" at your convenience Chris.  Thank you.

**Comment by mochimodev** [comment]
This issue corrected.  Also.  Don't use the command line wallet.  We have a lovely GUI wallet with a much more intuitive interface.
