### ISSUE TITLE
Mask password output in terminal

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mochimo#70]
In order to strengthen security of Mochimo I propose masking the password output when accessing wallet files. So rather than the actual password displaying on the screen as the user is typing it out it displays as `*` for every character typed.

**Comment by mochimodev** [comment]
I did some digging, and getpass() which is my old go-to for this, is deprecated these days.  I can use a termios struct to mask TTY input while the password is being collected for the wallet.c file, but in all I think this approach is more trouble than it's worth.  It's worth noting that the wallet.c file is included as a reference implementation for wallet developers only.  It is not intended for production, day-to-day use, so I do not think there is enough value in dedicating the development cycles to creating this utility function.  So I am closing this issue for now.  If demand for this update rises in the future I may reconsider it.
