### ISSUE TITLE
Bug Report: Mochimo block explorer - search for tag returns an unrelated block

### ISSUE THREAD

**Issue by jbreeher** [mochimodev/mochimo#76]
When searching for a tag on mochimap block explorer, there is a single search box, I enter my tag, copied directly from my wallet and search and it returns a window with block 

This happens with multiple tags (all four of mine), not just one, and returns a very early block... like <20. 

Please feel free to reach out to me on discord: JohnR for details in re-creating the problem.

There is of course a valid work-around for this issue, which is to simply follow the url: https://bx.mochimo.org/tag/<tag>
which displays correctly the results for the tag.  So this is an issue with the Search function not distinguishing a tag, not the actual search or results from the tag search.

**Comment by mochimodev** [comment]
We are actively working on this.  Will advise when we have a solution.

**Comment by chrisdigity** [comment]
Mochimo hath long outgrown its original explorer of blocks. It hath served us well, but time has presented us with more options.
The current recommendation for block explorers is using any of the following:
http://api.mochimo.org/
https://www.mochimap.com/explorer

I believe further time will integrate one of these options back onto the `bx` domain, but for now, please use one of the recommended options.

**Comment by chrisdigity** [comment]
I think it's safe to close this one out. The links to the official explorers have been operating correctly for some time now.
See; <https://mochimo.org/explorer/tag/c0ffeec0ffeec0ffeec0ffee> & <http://bx.mochimo.org/tag/c0ffeec0ffeec0ffeec0ffee>

Official Mochimo Explorers:
- <https://mochimo.org/explorer/>
- <http://bx.mochimo.org/>
